/**
 * gemstoneController.js — GET /api/gemstones + GET /api/gemstones/:slug  (ESM)
 */

const GEMSTONES = [
  {
    slug: "cats-eye",
    name: "Cat's Eye",
    sanskrit: "Lehsuniya",
    planet: "Ketu",
    color: "#ca8a04",
    tagline: "Spiritual liberation, intuition, and Ketu's mystical power.",
    properties: ["Intuition", "Spirituality", "Liberation", "Protection"],
    rashi: ["Sagittarius", "Pisces"],
    weight: "3–6 carats",
    metal: "Gold or Silver",
    finger: "Little finger",
    day: "Thursday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_Cat_sEye_composed_1080x.png",
  },
  {
    slug: "pearl",
    name: "Pearl",
    sanskrit: "Moti",
    planet: "Moon",
    color: "#94a3b8",
    tagline: "Emotional balance, intuition, and lunar grace.",
    properties: ["Calm", "Intuition", "Relationships", "Memory"],
    rashi: ["Cancer", "Scorpio", "Pisces"],
    weight: "4–6 carats",
    metal: "Silver",
    finger: "Little finger (right hand)",
    day: "Monday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_Pearl_composed_1080x.png",
  },
  {
    slug: "white-pukhraj",
    name: "White Pukhraj",
    sanskrit: "Shwet Pukhraj",
    planet: "Venus",
    color: "#e2e8f0",
    tagline: "Vedic alternative to Diamond, invoking Venusian luxury and creative harmony.",
    properties: ["Luxury", "Creativity", "Beauty", "Relationships"],
    rashi: ["Taurus", "Libra"],
    weight: "3–5 carats",
    metal: "White Gold or Silver",
    finger: "Ring or Middle finger",
    day: "Friday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_White_Pukhraj_composed_1080x.png",
  },
  {
    slug: "ceylon-pukhraj",
    name: "Ceylon Pukhraj",
    sanskrit: "Ceylon Pukhraj",
    planet: "Jupiter",
    color: "#fbbf24",
    tagline: "Premium Sri Lankan Yellow Sapphire for wisdom, health, and prosperity.",
    properties: ["Wisdom", "Wealth", "Divine Grace", "Good Fortune"],
    rashi: ["Sagittarius", "Pisces"],
    weight: "3–6 carats",
    metal: "Gold",
    finger: "Index finger",
    day: "Thursday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_Ceylon_Pukhraj_composed_1080x.png",
  },
  {
    slug: "peetambari-neelam",
    name: "Peetambari Neelam",
    sanskrit: "Peetambari",
    planet: "Jupiter & Saturn",
    color: "#8b5cf6",
    tagline: "Rare bi-color sapphire combining the forces of Jupiter and Saturn.",
    properties: ["Balance", "Karmic Justice", "Wealth", "Discernment"],
    rashi: ["Capricorn", "Aquarius", "Sagittarius", "Pisces"],
    weight: "3–5 carats",
    metal: "Gold or Panchdhatu",
    finger: "Middle finger",
    day: "Thursday or Saturday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_Peetambari_Neelam_composed_1080x.png",
  },
  {
    slug: "ceylon-neelam",
    name: "Ceylon Neelam",
    sanskrit: "Ceylon Neelam",
    planet: "Saturn",
    color: "#1d4ed8",
    tagline: "High-grade Sri Lankan Blue Sapphire for instant karmic elevation.",
    properties: ["Focus", "Karmic Cleansing", "Success", "Protection"],
    rashi: ["Capricorn", "Aquarius"],
    weight: "3–5 carats",
    metal: "Silver or Gold",
    finger: "Middle finger",
    day: "Saturday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_Ceylon_Neelam_composed_1080x.png",
  },
  {
    slug: "neelam",
    name: "Neelam",
    sanskrit: "Neelam",
    planet: "Saturn",
    color: "#2563eb",
    tagline: "The enforcer of Saturn's discipline and success.",
    properties: ["Discipline", "Justice", "Protection", "Focus"],
    rashi: ["Capricorn", "Aquarius"],
    weight: "3–5 carats",
    metal: "Silver or Panchdhatu",
    finger: "Middle finger",
    day: "Saturday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_Neelam_composed_1080x.png",
  },
  {
    slug: "emerald",
    name: "Emerald",
    sanskrit: "Panna",
    planet: "Mercury",
    color: "#059669",
    tagline: "Intelligence, communication, and Mercury's brilliance.",
    properties: ["Intelligence", "Creativity", "Business", "Communication"],
    rashi: ["Gemini", "Virgo"],
    weight: "3–5 carats",
    metal: "Gold",
    finger: "Little finger",
    day: "Wednesday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_Emerald_composed_1080x.png",
  },
  {
    slug: "burmese-ruby",
    name: "Burmese Ruby",
    sanskrit: "Burma Manikya",
    planet: "Sun",
    color: "#be123c",
    tagline: "Ultra-premium Burmese Ruby for maximum solar power and vitality.",
    properties: ["Royal Status", "Self-Expression", "Vitality", "Authority"],
    rashi: ["Leo", "Aries", "Scorpio"],
    weight: "2–4 carats",
    metal: "Gold",
    finger: "Ring finger",
    day: "Sunday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_Burmese_Ruby_composed_1080x.png",
  },
  {
    slug: "ruby",
    name: "Ruby",
    sanskrit: "Manikya",
    planet: "Sun",
    color: "#e11d48",
    tagline: "The stone of kings, solar vitality, and divine authority.",
    properties: ["Leadership", "Confidence", "Vitality", "Success"],
    rashi: ["Leo", "Aries", "Scorpio"],
    weight: "3–6 carats",
    metal: "Gold",
    finger: "Ring finger (right hand)",
    day: "Sunday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_Ruby_composed_1080x.png",
  },
  {
    slug: "australian-fire-opal",
    name: "Australian Fire Opal",
    sanskrit: "Opal",
    planet: "Venus",
    color: "#38bdf8",
    tagline: "Exquisite Australian Opal representing luxury, glamour, and beauty.",
    properties: ["Glamour", "Love", "Luxury", "Creative Mastery"],
    rashi: ["Taurus", "Libra"],
    weight: "5–8 carats",
    metal: "Silver or White Gold",
    finger: "Ring or Index finger",
    day: "Friday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_Australian_Fire_Opal_composed_1080x.png",
  },
  {
    slug: "fire-opal",
    name: "Fire Opal",
    sanskrit: "Opal",
    planet: "Venus",
    color: "#f97316",
    tagline: "The fiery stone of artistic inspiration and marital bliss.",
    properties: ["Passion", "Aesthetics", "Relationships", "Joy"],
    rashi: ["Taurus", "Libra"],
    weight: "4–7 carats",
    metal: "Silver",
    finger: "Ring finger",
    day: "Friday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_Fire_Opal_composed_1080x.png",
  },
  {
    slug: "blue-topaz",
    name: "Blue Topaz",
    sanskrit: "Pushparag Uparatna",
    planet: "Jupiter",
    color: "#60a5fa",
    tagline: "A peaceful substitute for Pukhraj to enhance communication and wisdom.",
    properties: ["Intellect", "Communication", "Mental Peace", "Learning"],
    rashi: ["Sagittarius", "Pisces"],
    weight: "5–10 carats",
    metal: "Silver",
    finger: "Index or Middle finger",
    day: "Thursday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_Blue_Topaz_composed_1080x.png",
  },
  {
    slug: "white-topaz",
    name: "White Topaz",
    sanskrit: "Dantur",
    planet: "Venus",
    color: "#f1f5f9",
    tagline: "Clear cosmic substitute for Venusian energy and creative clarity.",
    properties: ["Clarity", "Creative Flow", "Harmony", "Vitality"],
    rashi: ["Taurus", "Libra"],
    weight: "5–8 carats",
    metal: "Silver",
    finger: "Ring finger",
    day: "Friday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_White_Topaz_composed_1080x.png",
  },
  {
    slug: "natural-zircon",
    name: "Natural Zircon",
    sanskrit: "Zircon",
    planet: "Venus",
    color: "#e2e8f0",
    tagline: "Ancient, highly refractive alternative to Diamond for wealth and glamour.",
    properties: ["Magnetic Aura", "Material Wealth", "Happiness", "Arts"],
    rashi: ["Taurus", "Libra"],
    weight: "4–7 carats",
    metal: "Silver",
    finger: "Ring finger",
    day: "Friday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_Natural_Zircon_composed_1080x.png",
  },
  {
    slug: "zirconia",
    name: "Zirconia",
    sanskrit: "Kritrim Diamond",
    planet: "Venus (Substitute)",
    color: "#f8fafc",
    tagline: "Affordable modern alternative for channeling light Venusian vibes.",
    properties: ["Aesthetic appeal", "Youthfulness", "Modern Luck", "Lightness"],
    rashi: ["Taurus", "Libra"],
    weight: "4–8 carats",
    metal: "Silver",
    finger: "Middle or Ring finger",
    day: "Friday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_Zirconia_composed_1080x.png",
  },
  {
    slug: "garnet",
    name: "Garnet",
    sanskrit: "Tamra",
    planet: "Rahu",
    color: "#991b1b",
    tagline: "Grounding protection, ambition, and Rahu's drive.",
    properties: ["Energy", "Rahu Protection", "Root Healing", "Fame"],
    rashi: ["Aquarius", "Taurus", "Libra"],
    weight: "4–8 carats",
    metal: "Silver",
    finger: "Middle finger",
    day: "Saturday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_Garnet_composed_1080x.png",
  },
  {
    slug: "lapis-lazuli",
    name: "Lapis Lazuli",
    sanskrit: "Rajavarta",
    planet: "Saturn (Uparatna)",
    color: "#1e3a8a",
    tagline: "The royal blue stone of inner truth, wisdom, and Saturnian protection.",
    properties: ["Truth", "Third Eye", "Protection", "Wisdom"],
    rashi: ["Capricorn", "Aquarius"],
    weight: "6–10 carats",
    metal: "Silver",
    finger: "Middle finger",
    day: "Saturday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_Lapis_Lazuli_composed_1080x.png",
  },
  {
    slug: "turquoise",
    name: "Turquoise",
    sanskrit: "Firoza",
    planet: "Jupiter & Venus",
    color: "#06b6d4",
    tagline: "The legendary talisman of travel safety, health, and spiritual growth.",
    properties: ["Protection", "Healing", "Wealth", "Travel Safety"],
    rashi: ["Sagittarius", "Pisces", "Taurus", "Libra"],
    weight: "5–10 carats",
    metal: "Silver",
    finger: "Ring or Little finger",
    day: "Thursday or Friday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_Turquoise_composed_1080x.png",
  },
  {
    slug: "moonstone",
    name: "Moonstone",
    sanskrit: "Chandrakant Mani",
    planet: "Moon (Uparatna)",
    color: "#e2e8f0",
    tagline: "The glowing lunar gem for emotional balance and divine feminine energy.",
    properties: ["Calm", "Feminine Energy", "Intuition", "Sleep"],
    rashi: ["Cancer"],
    weight: "5–8 carats",
    metal: "Silver",
    finger: "Little finger",
    day: "Monday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_Moonstone_composed_1080x.png",
  },
  {
    slug: "amethyst",
    name: "Amethyst",
    sanskrit: "Katela",
    planet: "Saturn (Uparatna)",
    color: "#7e22ce",
    tagline: "The stone of spiritual sobriety, meditative peace, and Saturn's grace.",
    properties: ["Sobriety", "Intuition", "Calmness", "Spiritual Growth"],
    rashi: ["Capricorn", "Aquarius"],
    weight: "4–8 carats",
    metal: "Silver",
    finger: "Middle finger",
    day: "Saturday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_Amethyst_composed_1080x.png",
  },
  {
    slug: "citrine",
    name: "Citrine",
    sanskrit: "Sunela",
    planet: "Jupiter (Uparatna)",
    color: "#eab308",
    tagline: "The merchant's stone of wealth, optimism, and solar plexus energy.",
    properties: ["Abundance", "Confidence", "Optimism", "Mental Focus"],
    rashi: ["Sagittarius", "Pisces"],
    weight: "4–8 carats",
    metal: "Gold or Silver",
    finger: "Index finger",
    day: "Thursday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_Citrine_composed_1080x.png",
  },
  {
    slug: "tiger-eye",
    name: "Tiger Eye",
    sanskrit: "Tiger Eye",
    planet: "Sun & Mars",
    color: "#a16207",
    tagline: "Courage, grounding focus, and absolute self-confidence.",
    properties: ["Willpower", "Protection", "Action", "Vitality"],
    rashi: ["Leo", "Aries", "Scorpio"],
    weight: "6–10 carats",
    metal: "Panchdhatu or Silver",
    finger: "Ring or Middle finger",
    day: "Sunday or Tuesday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_Tiger_Eye_composed_1080x.png",
  },
  {
    slug: "african-ruby",
    name: "African Ruby",
    sanskrit: "African Manikya",
    planet: "Sun",
    color: "#9f1239",
    tagline: "Deep, grounding African Ruby for leadership, courage, and vitality.",
    properties: ["Leadership", "Vitality", "Confidence", "Action"],
    rashi: ["Leo", "Aries", "Scorpio"],
    weight: "3–6 carats",
    metal: "Gold",
    finger: "Ring finger",
    day: "Sunday",
    image: "https://humarapandit.com/cdn/shop/files/1img0_African_Ruby_composed_1080x.png",
  }
];

export function getAllGemstones(_req, res) {
  return res.json(GEMSTONES);
}

export function getGemstoneBySlug(req, res) {
  const gem = GEMSTONES.find((g) => g.slug === req.params.slug);
  if (!gem) return res.status(404).json({ error: `Gemstone '${req.params.slug}' not found` });
  return res.json(gem);
}
