/**
 * gemstoneController.js — GET /api/gemstones + GET /api/gemstones/:slug  (ESM)
 */

const GEMSTONES = [
  {
    slug: "ruby",
    name: "Ruby",
    sanskrit: "Manikya",
    planet: "Sun",
    color: "#e11d48",
    tagline: "The stone of kings, solar vitality, and divine authority.",
    properties: ["Leadership", "Confidence", "Vitality", "Success", "Courage", "Fame"],
    rashi: ["Leo", "Aries", "Scorpio"],
    weight: "3–6 carats",
    metal: "Gold",
    finger: "Ring finger (right hand)",
    day: "Sunday",
  },
  {
    slug: "pearl",
    name: "Pearl",
    sanskrit: "Moti",
    planet: "Moon",
    color: "#94a3b8",
    tagline: "Emotional balance, intuition, and lunar grace.",
    properties: ["Calm", "Intuition", "Relationships", "Memory", "Peace"],
    rashi: ["Cancer", "Scorpio", "Pisces"],
    weight: "4–6 carats",
    metal: "Silver",
    finger: "Little finger (right hand)",
    day: "Monday",
  },
  {
    slug: "red-coral",
    name: "Red Coral",
    sanskrit: "Moonga",
    planet: "Mars",
    color: "#ea580c",
    tagline: "Courage, ambition, and the fire of Mars.",
    properties: ["Courage", "Energy", "Protection", "Determination"],
    rashi: ["Aries", "Scorpio"],
    weight: "6–12 carats",
    metal: "Gold or Copper",
    finger: "Ring finger",
    day: "Tuesday",
  },
  {
    slug: "emerald",
    name: "Emerald",
    sanskrit: "Panna",
    planet: "Mercury",
    color: "#059669",
    tagline: "Intelligence, communication, and Mercury's brilliance.",
    properties: ["Intelligence", "Creativity", "Business", "Communication"],
    rashi: ["Gemini", "Virgo"],
    weight: "3–5 carats",
    metal: "Gold",
    finger: "Little finger",
    day: "Wednesday",
  },
  {
    slug: "yellow-sapphire",
    name: "Yellow Sapphire",
    sanskrit: "Pukhraj",
    planet: "Jupiter",
    color: "#d97706",
    tagline: "Wisdom, prosperity, and Jupiter's boundless grace.",
    properties: ["Wisdom", "Prosperity", "Luck", "Spirituality"],
    rashi: ["Sagittarius", "Pisces"],
    weight: "3–6 carats",
    metal: "Gold",
    finger: "Index finger",
    day: "Thursday",
  },
  {
    slug: "diamond",
    name: "Diamond",
    sanskrit: "Heera",
    planet: "Venus",
    color: "#e2e8f0",
    tagline: "Love, luxury, artistic beauty, and Venusian allure.",
    properties: ["Love", "Luxury", "Creativity", "Harmony"],
    rashi: ["Taurus", "Libra"],
    weight: "0.5–1 carat",
    metal: "White Gold or Platinum",
    finger: "Middle finger",
    day: "Friday",
  },
  {
    slug: "blue-sapphire",
    name: "Blue Sapphire",
    sanskrit: "Neelam",
    planet: "Saturn",
    color: "#2563eb",
    tagline: "Discipline, karmic acceleration, and Saturn's iron will.",
    properties: ["Discipline", "Focus", "Career", "Justice"],
    rashi: ["Capricorn", "Aquarius"],
    weight: "3–5 carats",
    metal: "Silver or Gold",
    finger: "Middle finger",
    day: "Saturday",
  },
  {
    slug: "hessonite",
    name: "Hessonite",
    sanskrit: "Gomed",
    planet: "Rahu",
    color: "#92400e",
    tagline: "Protection from illusion, clarity, and Rahu's liberation.",
    properties: ["Clarity", "Protection", "Focus", "Ambition"],
    rashi: ["Gemini", "Virgo"],
    weight: "6–8 carats",
    metal: "Silver",
    finger: "Middle finger",
    day: "Saturday",
  },
  {
    slug: "cats-eye",
    name: "Cat's Eye",
    sanskrit: "Lehsuniya",
    planet: "Ketu",
    color: "#ca8a04",
    tagline: "Spiritual liberation, intuition, and Ketu's mystical power.",
    properties: ["Intuition", "Spirituality", "Liberation", "Protection"],
    rashi: ["Sagittarius", "Pisces"],
    weight: "3–6 carats",
    metal: "Gold or Silver",
    finger: "Little finger",
    day: "Thursday",
  },
];

export function getAllGemstones(_req, res) {
  return res.json(GEMSTONES);
}

export function getGemstoneBySlug(req, res) {
  const gem = GEMSTONES.find((g) => g.slug === req.params.slug);
  if (!gem) return res.status(404).json({ error: `Gemstone '${req.params.slug}' not found` });
  return res.json(gem);
}
